version: '3.8'

services:
  flask_app:
    build:
      context: .
    container_name: dz4_flask_container
    ports:
      - "5000:5000"
    volumes:
      - .:/src
    environment:
      - FLASK_ENV=development
    command: ["python", "app.py"]