version: '3.8'

services:
  flask_app:
    build:
      context: .
    container_name: dz4_flask_container
    ports:
      - "5000:5000"
    volumes:
      - .:/src
    environment:
      - FLASK_ENV=development
    command: ["python", "app.py"]
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
