# Generated by Django 5.1.4 on 2025-01-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskanswer",
            name="mark",
            field=models.PositiveIntegerField(default=0, verbose_name="Task mark"),
        ),
    ]
