# Generated by Django 5.1.4 on 2025-01-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_alter_taskanswer_mark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskanswer",
            name="mark",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Task mark"
            ),
        ),
    ]
