# Generated by Django 5.1.4 on 2025-01-28 17:57

from django.db import migrations
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType


def create_roles_and_permissions(apps, schema_editor):
    Course = apps.get_model("courses", "Course")
    Lesson = apps.get_model("lessons", "Lesson")
    Task = apps.get_model("tasks", "Task")
    TaskAnswer = apps.get_model("tasks", "TaskAnswer")
    User = apps.get_model("user", "User")

    admin_group, _ = Group.objects.get_or_create(name="Administrator")
    manager_group, _ = Group.objects.get_or_create(name="Manager")
    teacher_group, _ = Group.objects.get_or_create(name="Teacher")

    course_ct = ContentType.objects.get_for_model(Course)
    lesson_ct = ContentType.objects.get_for_model(Lesson)
    task_ct = ContentType.objects.get_for_model(Task)
    task_answer_ct = ContentType.objects.get_for_model(TaskAnswer)

    admin_permissions = Permission.objects.filter(
        content_type__model__in=["course", "lesson", "task", "taskanswer"]
    )
    admin_group.permissions.set(admin_permissions)

    manager_permissions = [
        Permission.objects.get(codename="add_lesson", content_type=lesson_ct),
    ]
    manager_group.permissions.set(manager_permissions)

    teacher_permissions = [
        Permission.objects.get(codename="view_course", content_type=course_ct),
        Permission.objects.get(codename="add_task", content_type=task_ct),
        Permission.objects.get(codename="view_taskanswer", content_type=task_answer_ct),
        Permission.objects.get(
            codename="change_taskanswer", content_type=task_answer_ct
        ),
    ]
    teacher_group.permissions.set(teacher_permissions)


def remove_roles_and_permissions(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name__in=["Administrator", "Manager", "Teacher"]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_initial"),
        ("lessons", "0001_initial"),
        ("tasks", "0002_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            create_roles_and_permissions, remove_roles_and_permissions
        ),
    ]
